version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "443:443"
    restart: always
    depends_on:
      - db
    volumes:
      - ./hosting:/etc/nginx/sites-available/

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sdproject
      MYSQL_ROOT_PASSWORD: Simform@123
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
